name: Mingw Build

on:
  push:
    paths-ignore:
      - '.gitignore'

jobs:
  mingw:
    name: Windows (MinGW)
    strategy:
      fail-fast: false
      matrix:
        msystem: [mingw64]
        os: [windows-latest]
        arch: [x86_64]
        mode: [debug, release]
        kind: [binary]

    runs-on: ${{ matrix.os }}
    if: ${{ contains(github.event.head_commit.message, 'ci run') || contains(github.event.head_commit.message, 'ci mingw') }}

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Get current date as package key
        id: cache_key
        shell: bash
        run: echo "key=$(date +'%W')" >> $GITHUB_OUTPUT

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Vulkan SDK
        uses: jakoch/install-vulkan-sdk-action@v1
        with:
          vulkan_version: 1.4.328.1
          optional_components: com.lunarg.vulkan.vma, com.lunarg.vulkan.debug
          install_runtime: true
          cache: true
          stripdown: true

      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          install: base-devel git unzip p7zip mingw-w64-${{ matrix.arch }}-toolchain mingw-w64-${{ matrix.arch }}-xmake
          update: true

      - name: Set xmake env
        run: echo "XMAKE_GLOBALDIR=${{ runner.workspace }}/xmake-global" >> $GITHUB_ENV

      - name: Update xmake repository
        run: xmake repo --update

      - name: Retrieve dependencies hash
        id: dep_hash
        run: echo "hash=$(xmake l utils.ci.packageskey)" >> $GITHUB_OUTPUT

      - name: Restore cached xmake dependencies
        id: restore-depcache
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.XMAKE_GLOBALDIR }}/.xmake/packages
          key: MinGW-${{ matrix.arch }}-${{ matrix.mode }}-${{ steps.dep_hash.outputs.hash }}-W${{ steps.cache_key.outputs.key }}

      - name: Configure xmake and install dependencies
        run: xmake config --arch=${{ matrix.arch }} --mode=${{ matrix.mode }} --ccache=n --yes

      - name: Save cached xmake dependencies
        if: ${{ !steps.restore-depcache.outputs.cache-hit }}
        uses: actions/cache/save@v4
        with:
          path: ${{ env.XMAKE_GLOBALDIR }}/.xmake/packages
          key: ${{ steps.restore-depcache.outputs.cache-primary-key }}

      - name: Build
        run: xmake -v --yes